Use Forge crop events
progwml6/Natura pull request #456
Opened 2018-06-22 21:48 UTC by Stormwind99

Fix for #455 Natura crops, bush, cactus growing not using Forge's onCropsGrowPre/Post events, breaking compatibility with some mods

Also small gradle settings fix and possible README.md markdown detection fix

2018-07-18 22:40 UTC, progwml6 requested changes

2018-07-18 22:40 UTC, progwml6 commented on settings.gradle
> +rootProject.name = 'Natura'
Do not change this

2018-07-19 05:19 UTC, Stormwind99 commented on settings.gradle
> +rootProject.name = 'Natura'
Changed back - but a warning that my environment won't build a clean checkout of Natura without that change.

2018-07-19 05:23 UTC, Stormwind99 commented on settings.gradle
> +rootProject.name = 'Natura'
Changed back.  Just a warning though that my build environment (Forge MDK, gradle, Eclipse) could not build a clean checkout of Natura without that change.

2018-07-22 00:56 UTC, merged